const dummyData = [
  {
    'id': 0,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'RS BPJS 1',
    'address': 'Jalan BPJS 1',
    'type': 'Rumah Sakit',
    'category': 'BPJS',
  },
  {
    'id': 1,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'RS BPJS 2',
    'address': 'Jalan BPJS 2',
    'type': 'Rumah Sakit',
    'category': 'BPJS',
  },
  {
    'id': 2,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'RS Patner 1',
    'address': 'Jalan Patner 1',
    'type': 'Rumah Sakit',
    'category': 'Patner',
  },
  {
    'id': 3,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'RS Patner 2',
    'address': 'Jalan Patner 2',
    'type': 'Rumah Sakit',
    'category': 'Patner',
  },
  {
    'id': 4,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'RS Patner 3',
    'address': 'Jalan Patner 3',
    'type': 'Rumah Sakit',
    'category': 'Patner',
  },
  {
    'id': 5,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'RS Terdekat 1',
    'address': 'Jalan Terdekat 1',
    'type': 'Rumah Sakit',
    'category': 'Terdekat',
  },
  {
    'id': 6,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'RS Terdekat 2',
    'address': 'Jalan Terdekat 2',
    'type': 'Rumah Sakit',
    'category': 'Terdekat',
  },

  {
    'id': 7,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'Klinik BPJS 1',
    'address': 'Jalan Klinik BPJS 1',
    'type': 'Klinik',
    'category': 'BPJS',
  },
  {
    'id': 8,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'Klinik BPJS 2',
    'address': 'Jalan Klinik BPJS 2',
    'type': 'Klinik',
    'category': 'BPJS',
  },
  {
    'id': 9,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'Klinik BPJS 3',
    'address': 'Jalan Klinik BPJS 3',
    'type': 'Klinik',
    'category': 'BPJS',
  },
  {
    'id': 10,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'Klinik Patner 1',
    'address': 'Jalan Klinik Patner 1',
    'type': 'Klinik',
    'category': 'Patner',
  },
  {
    'id': 11,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'Klinik Patner 2',
    'address': 'Jalan Klinik Patner 2',
    'type': 'Klinik',
    'category': 'Patner',
  },
  {
    'id': 12,
    'image': 'assets/images/flutter-logo.jpg',
    'name': 'Klinik Terdekat 1',
    'address': 'Jalan Klinik Terdekat 1',
    'type': 'Klinik',
    'category': 'Terdekat',
  },
];